sudo: true

dist: trusty

services:
- docker

language: ruby

cache:
  bundler
  directories:
  - /home/travis/.rvm/  
  - $HOME/.local

rvm:
- 2.5.1

before_install:
  - pip install --local awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  - eval $(aws ecr get-login --region eu-west-1 
  - sudo apt-get update && sudo apt-get install -y apt-transport-https
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get install -y kubectl

deploy:
  provider: script
  script: bash ./release.sh -r ${REPO} 
  on:
    tags: true