sudo: true

dist: trusty

services:
- docker

language: ruby

cache:
  bundler
  directories:
  - /home/travis/.rvm/  
  - $HOME/.local

rvm:
- 2.5.1

before_install:
  - pip install --local aws-cli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash ./release.sh -r ${REPO} 
  on:
    tags: true