sudo: true
dist: trusty
services:
- docker
language: ruby
rvm:
- 2.5.1
deploy:
  skip_cleanup: true
jobs:
  include:
  - stage: run tests
  - stage: release if newer than version already deployed
    script: ./release.sh -r ${REPO}
