dist: trusty
sudo: required

services:
- docker

language: ruby
cache: 
  bundle: true
  directories:
  - node_modules # NPM packages
  - ./vendor/bundle

python:
- 2.7.13
rvm:
- 2.5.1

before_deploy:
- ./prepare.sh

deploy:
  provider: script
  script: bash ./release.sh -r ${REPO} 
  on:
    tags: true
